repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        name: ruff lint, sort, and fix
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: black code formatter
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: mypy type checker

  - repo: local
    hooks:
      - id: pytest
        name: pytest tests
        entry: ./.venv/bin/pytest tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
