from typing import Literal


RESERVED = {
    "@",
    "me",
    "profile",
    "settings",
    "account",
    "dashboard",
    "login",
    "logout",
    "signup",
    "register",
    "password",
    "forgot",
    "reset",
    "verify",
    "2fa",
    "mfa",
    "auth",
    "oauth",
    "callback",
    "callbacks",
    "admin",
    "root",
    "sysadmin",
    "staff",
    "support",
    "help",
    "moderator",
    "mod",
    "team",
    "teams",
    "dev",
    "developer",
    "developers",
    "api",
    "v1",
    "v2",
    "graphql",
    "docs",
    "status",
    "health",
    "metrics",
    "ping",
    "webhook",
    "webhooks",
    "static",
    "assets",
    "img",
    "images",
    "css",
    "js",
    "fonts",
    "media",
    "uploads",
    "cdn",
    "robots",
    "sitemap",
    "favicon",
    "well-known",
    "about",
    "privacy",
    "terms",
    "legal",
    "security",
    "policies",
    "pricing",
    "jobs",
    "careers",
    "press",
    "blog",
    "news",
    "contact",
    "new",
    "create",
    "edit",
    "delete",
    "update",
    "report",
    "reports",
    "billing",
    "payments",
    "subscribe",
    "unsubscribe",
    "owner",
    "system",
    "service",
    "bot",
    "null",
    "undefined",
    "none",
    "true",
    "false",
    "con",
    "prn",
    "aux",
    "nul",
    *{f"com{i}" for i in range(1, 10)},
    *{f"lpt{i}" for i in range(1, 10)},
}

WATCHLIST_VISIBILITY = Literal["private", "public", "shared"]

STOCK_INTERVALS = {
    "1m",
    "2m",
    "5m",
    "15m",
    "30m",
    "60m",
    "90m",
    "1h",
    "1d",
    "5d",
    "1wk",
    "1mo",
    "3mo",
}

STOCK_PERIODS = {"1d", "5d", "1mo", "3mo", "6mo", "1y", "2y", "5y", "ytd", "max"}

MARKETS = {"US", "GB", "ASIA", "EUROPE", "RATES", "COMMODITIES", "CURRENCIES", "CRYPTOCURRENCIES"}